CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date, PRIMARY KEY (ID));
CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date, PRIMARY KEY (FIRSTNAME));
SELECT FIRSTSEASON, COUNT(ID) 
FROM PLAYERS 
GROUP BY FIRSTSEASON;
